 Network rinha-2024q1  Creating
 Network rinha-2024q1  Created
 Container rinhadb  Creating
 Container rinhadb  Created
 Container rinhaapi1  Creating
 Container rinhaapi2  Creating
 Container rinhaapi1  Created
 Container rinhaapi2  Created
 Container rinha-cleidiano-nginx-1  Creating
 Container rinha-cleidiano-nginx-1  Created
Attaching to nginx-1, rinhaapi1, rinhaapi2, rinhadb
rinhadb    | The files belonging to this database system will be owned by user "postgres".
rinhadb    | This user must also own the server process.
rinhadb    | 
rinhadb    | The database cluster will be initialized with locale "en_US.utf8".
rinhadb    | The default database encoding has accordingly been set to "UTF8".
rinhadb    | The default text search configuration will be set to "english".
rinhadb    | 
rinhadb    | Data page checksums are disabled.
rinhadb    | 
rinhadb    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rinhadb    | creating subdirectories ... ok
rinhadb    | selecting dynamic shared memory implementation ... posix
rinhadb    | selecting default max_connections ... 100
rinhadb    | selecting default shared_buffers ... 128MB
rinhadb    | selecting default time zone ... Etc/UTC
rinhadb    | creating configuration files ... ok
rinhadb    | running bootstrap script ... ok
rinhadb    | performing post-bootstrap initialization ... ok
rinhadb    | syncing data to disk ... ok
rinhadb    | 
rinhadb    | 
rinhadb    | Success. You can now start the database server using:
rinhadb    | 
rinhadb    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rinhadb    | 
rinhadb    | initdb: warning: enabling "trust" authentication for local connections
rinhadb    | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rinhadb    | waiting for server to start....2024-03-09 01:22:18.658 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinhadb    | 2024-03-09 01:22:18.658 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinhadb    | 2024-03-09 01:22:18.659 UTC [52] LOG:  database system was shut down at 2024-03-09 01:22:18 UTC
rinhadb    | 2024-03-09 01:22:18.662 UTC [49] LOG:  database system is ready to accept connections
rinhadb    |  done
rinhadb    | server started
rinhadb    | CREATE DATABASE
rinhadb    | 
rinhadb    | 
rinhadb    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01-ddl.sql
rinhadb    | SET
rinhadb    | SET
rinhadb    | SET
rinhadb    | SET
rinhadb    | SET
rinhadb    | CREATE TABLE
rinhadb    | CREATE TABLE
rinhadb    | CREATE INDEX
rinhadb    | 
rinhadb    | 
rinhadb    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/11-criartransacao.sql
rinhadb    | CREATE FUNCTION
rinhadb    | 
rinhadb    | 
rinhadb    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/21-resetdb.sql
rinhadb    | TRUNCATE TABLE
rinhadb    | TRUNCATE TABLE
rinhadb    | INSERT 0 1
rinhadb    | INSERT 0 1
rinhadb    | INSERT 0 1
rinhadb    | INSERT 0 1
rinhadb    | INSERT 0 1
rinhadb    | 
rinhadb    | 
rinhadb    | waiting for server to shut down...2024-03-09 01:22:19.034 UTC [49] LOG:  received fast shutdown request
rinhadb    | .2024-03-09 01:22:19.034 UTC [49] LOG:  aborting any active transactions
rinhadb    | 2024-03-09 01:22:19.035 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
rinhadb    | 2024-03-09 01:22:19.036 UTC [50] LOG:  shutting down
rinhadb    | 2024-03-09 01:22:19.036 UTC [50] LOG:  checkpoint starting: shutdown immediate
rinhadb    | 2024-03-09 01:22:19.051 UTC [50] LOG:  checkpoint complete: wrote 935 buffers (14.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.016 s, sync=0.001 s, total=0.016 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4285 kB, estimate=4285 kB; lsn=0/191A028, redo lsn=0/191A028
rinhadb    | 2024-03-09 01:22:19.055 UTC [49] LOG:  database system is shut down
rinhadb    |  done
rinhadb    | server stopped
rinhadb    | 
rinhadb    | PostgreSQL init process complete; ready for start up.
rinhadb    | 
rinhadb    | 2024-03-09 01:22:19.147 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinhadb    | 2024-03-09 01:22:19.147 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rinhadb    | 2024-03-09 01:22:19.147 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rinhadb    | 2024-03-09 01:22:19.147 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinhadb    | 2024-03-09 01:22:19.149 UTC [71] LOG:  database system was shut down at 2024-03-09 01:22:19 UTC
rinhadb    | 2024-03-09 01:22:19.152 UTC [1] LOG:  database system is ready to accept connections
nginx-1    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1    | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1    | /docker-entrypoint.sh: Configuration complete; ready for start up
rinhaapi1  | 2024-03-09 01:22:24.828 [main] INFO  io.ebean - ebean version: 13.26.1
rinhaapi2  | 2024-03-09 01:22:24.926 [main] INFO  io.ebean - ebean version: 13.26.1
rinhaapi1  | 2024-03-09 01:22:25.122 [main] INFO  io.avaje.config - Loaded properties from [resource:application.yaml] 
nginx-1    | 2024/03/09 01:22:25 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1    | 2024/03/09 01:22:25 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:8080/clientes/1/extrato", host: "localhost:9999"
rinhaapi2  | 2024-03-09 01:22:25.224 [main] INFO  io.avaje.config - Loaded properties from [resource:application.yaml] 
rinhaapi1  | 2024-03-09 01:22:26.916 [main] INFO  io.ebean.datasource - DataSource [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[5] in[1,383ms]
rinhaapi2  | 2024-03-09 01:22:27.019 [main] INFO  io.ebean.datasource - DataSource [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[5] in[1,393ms]
nginx-1    | 2024/03/09 01:22:27 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinhaapi1  | 2024-03-09 01:22:28.725 [main] INFO  io.ebean.core - Started database[db] platform[POSTGRES] in 3,402ms
rinhaapi2  | 2024-03-09 01:22:28.816 [main] INFO  io.ebean.core - Started database[db] platform[POSTGRES] in 3,397ms
rinhaapi1  | 2024-03-09 01:22:29.137 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
nginx-1    | 2024/03/09 01:22:29 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinhaapi2  | 2024-03-09 01:22:29.228 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
rinhaapi1  | 2024-03-09 01:22:30.926 [main] INFO  ktor.application - Application started in 1.9 seconds.
rinhaapi2  | 2024-03-09 01:22:31.119 [main] INFO  ktor.application - Application started in 2.089 seconds.
nginx-1    | 2024/03/09 01:22:31 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinhaapi1  | 2024-03-09 01:22:31.622 [DefaultDispatcher-worker-1] INFO  ktor.application - Responding at http://0.0.0.0:8080
rinhaapi2  | 2024-03-09 01:22:31.730 [DefaultDispatcher-worker-1] INFO  ktor.application - Responding at http://0.0.0.0:8080
nginx-1    | 2024/03/09 01:22:33 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1    | 2024/03/09 01:22:35 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
rinhaapi1  | 2024-03-09 01:26:50.541 [EbeanHook] INFO  io.ebean.datasource - DataSource [db] shutdown min[2] max[5] free[5] busy[0] waiting[0] highWaterMark[5] waitCount[95] hitCount[30737]  psc[hit:31,491 miss:16 put:31,507 rem:0]
rinhaapi2  | 2024-03-09 01:26:50.546 [EbeanHook] INFO  io.ebean.datasource - DataSource [db] shutdown min[2] max[5] free[5] busy[0] waiting[0] highWaterMark[5] waitCount[101] hitCount[30765]  psc[hit:31,854 miss:16 put:31,870 rem:0]
rinhaapi1 exited with code 0
rinhaapi1 exited with code 143
rinhaapi2 exited with code 0
rinhaapi2 exited with code 143
rinhadb    | 2024-03-09 01:26:52.378 UTC [1] LOG:  received fast shutdown request
rinhadb    | 2024-03-09 01:26:52.378 UTC [1] LOG:  aborting any active transactions
rinhadb    | 2024-03-09 01:26:52.380 UTC [1] LOG:  background worker "logical replication launcher" (PID 74) exited with exit code 1
rinhadb    | 2024-03-09 01:26:52.381 UTC [69] LOG:  shutting down
rinhadb    | 2024-03-09 01:26:52.381 UTC [69] LOG:  checkpoint starting: shutdown immediate
rinhadb    | 2024-03-09 01:26:52.384 UTC [69] LOG:  checkpoint complete: wrote 673 buffers (10.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=1929 kB, estimate=1929 kB; lsn=0/1AFC4C8, redo lsn=0/1AFC4C8
rinhadb    | 2024-03-09 01:26:52.387 UTC [1] LOG:  database system is shut down
rinhadb exited with code 0
