 Network rinha-nginx-2024-q1  Creating
 Network rinha-nginx-2024-q1  Created
 Container db  Creating
 Container db  Created
 Container api02  Creating
 Container api01  Creating
 Container api01  Created
 Container api02  Created
 Container adolfoweloy-nginx-1  Creating
 Container adolfoweloy-nginx-1  Created
Attaching to nginx-1, api01, api02, db
db       | The files belonging to this database system will be owned by user "postgres".
db       | This user must also own the server process.
db       | 
db       | The database cluster will be initialized with locale "en_US.utf8".
db       | The default database encoding has accordingly been set to "UTF8".
db       | The default text search configuration will be set to "english".
db       | 
db       | Data page checksums are disabled.
db       | 
db       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db       | creating subdirectories ... ok
db       | selecting dynamic shared memory implementation ... posix
db       | selecting default max_connections ... 100
db       | selecting default shared_buffers ... 128MB
db       | selecting default time zone ... Etc/UTC
db       | creating configuration files ... ok
db       | running bootstrap script ... ok
db       | performing post-bootstrap initialization ... ok
db       | syncing data to disk ... ok
db       | 
db       | 
db       | Success. You can now start the database server using:
db       | 
db       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db       | 
db       | initdb: warning: enabling "trust" authentication for local connections
db       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db       | waiting for server to start....2024-03-10 16:14:40.636 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db       | 2024-03-10 16:14:40.639 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db       | 2024-03-10 16:14:40.648 UTC [51] LOG:  database system was shut down at 2024-03-10 16:14:40 UTC
db       | 2024-03-10 16:14:40.654 UTC [48] LOG:  database system is ready to accept connections
db       |  done
db       | server started
db       | CREATE DATABASE
db       | 
db       | 
db       | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
db       | CREATE SEQUENCE
db       | CREATE TABLE
db       | ALTER SEQUENCE
db       | CREATE SEQUENCE
db       | CREATE TABLE
db       | ALTER SEQUENCE
db       | DO
db       | 
db       | 
db       | waiting for server to shut down...2024-03-10 16:14:40.966 UTC [48] LOG:  received fast shutdown request
db       | .2024-03-10 16:14:40.969 UTC [48] LOG:  aborting any active transactions
db       | 2024-03-10 16:14:41.018 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db       | 2024-03-10 16:14:41.018 UTC [49] LOG:  shutting down
db       | 2024-03-10 16:14:41.021 UTC [49] LOG:  checkpoint starting: shutdown immediate
db       | 2024-03-10 16:14:41.522 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.416 s, sync=0.075 s, total=0.505 s; sync files=307, longest=0.045 s, average=0.001 s; distance=4298 kB, estimate=4298 kB; lsn=0/191D2C8, redo lsn=0/191D2C8
db       | 2024-03-10 16:14:41.527 UTC [48] LOG:  database system is shut down
db       |  done
db       | server stopped
db       | 
db       | PostgreSQL init process complete; ready for start up.
db       | 
db       | 2024-03-10 16:14:41.595 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db       | 2024-03-10 16:14:41.595 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db       | 2024-03-10 16:14:41.595 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db       | 2024-03-10 16:14:41.600 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db       | 2024-03-10 16:14:41.607 UTC [66] LOG:  database system was shut down at 2024-03-10 16:14:41 UTC
db       | 2024-03-10 16:14:41.615 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1  | 2024/03/10 16:14:46 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.160.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:14:46 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.160.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:14:48 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01    | 
api01    |   .   ____          _            __ _ _
api01    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api01    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api01    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api01    |   '  |____| .__|_| |_|_| |_\__, | / / / /
api01    |  =========|_|==============|___/=/_/_/_/
api01    |  :: Spring Boot ::                (v3.2.3)
api01    | 
api02    | 
api02    |   .   ____          _            __ _ _
api02    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api02    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api02    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api02    |   '  |____| .__|_| |_|_| |_\__, | / / / /
api02    |  =========|_|==============|___/=/_/_/_/
api02    |  :: Spring Boot ::                (v3.2.3)
api02    | 
api01    | 2024-03-10T16:14:50.218Z  INFO 1 --- [           main] c.a.r.RinhabackendApplication            : Starting RinhabackendApplication v0.0.1-SNAPSHOT using Java 21.0.2 with PID 1 (/opt/rinhabackend/rinha.jar started by root in /opt/rinhabackend)
api01    | 2024-03-10T16:14:50.222Z  INFO 1 --- [           main] c.a.r.RinhabackendApplication            : No active profile set, falling back to 1 default profile: "default"
api02    | 2024-03-10T16:14:50.418Z  INFO 1 --- [           main] c.a.r.RinhabackendApplication            : Starting RinhabackendApplication v0.0.1-SNAPSHOT using Java 21.0.2 with PID 1 (/opt/rinhabackend/rinha.jar started by root in /opt/rinhabackend)
api02    | 2024-03-10T16:14:50.421Z  INFO 1 --- [           main] c.a.r.RinhabackendApplication            : No active profile set, falling back to 1 default profile: "default"
nginx-1  | 2024/03/10 16:14:50 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:14:52 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01    | 2024-03-10T16:14:53.632Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
api01    | 2024-03-10T16:14:54.020Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 302 ms. Found 2 JPA repository interfaces.
api02    | 2024-03-10T16:14:54.126Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
api02    | 2024-03-10T16:14:54.421Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 206 ms. Found 2 JPA repository interfaces.
nginx-1  | 2024/03/10 16:14:54 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:14:56 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01    | 2024-03-10T16:14:57.122Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
api01    | 2024-03-10T16:14:57.141Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api01    | 2024-03-10T16:14:57.215Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.19]
api02    | 2024-03-10T16:14:57.630Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
api02    | 2024-03-10T16:14:57.726Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api02    | 2024-03-10T16:14:57.726Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.19]
api01    | 2024-03-10T16:14:57.731Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api01    | 2024-03-10T16:14:57.733Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7304 ms
api02    | 2024-03-10T16:14:58.316Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api02    | 2024-03-10T16:14:58.317Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7684 ms
nginx-1  | 2024/03/10 16:14:58 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.160.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:14:58 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.160.3:8080/clientes/1/extrato", host: "localhost:9999"
api01    | 2024-03-10T16:14:59.435Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
api01    | 2024-03-10T16:14:59.636Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.4.Final
api01    | 2024-03-10T16:14:59.743Z  INFO 1 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
api02    | 2024-03-10T16:15:00.132Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
api02    | 2024-03-10T16:15:00.335Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.4.Final
api02    | 2024-03-10T16:15:00.525Z  INFO 1 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
nginx-1  | 2024/03/10 16:15:00 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01    | 2024-03-10T16:15:01.119Z  INFO 1 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
api01    | 2024-03-10T16:15:01.148Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api02    | 2024-03-10T16:15:01.544Z  INFO 1 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
api02    | 2024-03-10T16:15:01.642Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api01    | 2024-03-10T16:15:02.116Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@d120d7c
api01    | 2024-03-10T16:15:02.117Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api01    | 2024-03-10T16:15:02.224Z  WARN 1 --- [           main] org.hibernate.orm.deprecation            : HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
api02    | 2024-03-10T16:15:02.341Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@5ee77baf
api02    | 2024-03-10T16:15:02.342Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api02    | 2024-03-10T16:15:02.423Z  WARN 1 --- [           main] org.hibernate.orm.deprecation            : HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
nginx-1  | 2024/03/10 16:15:02 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:04 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:06 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02    | 2024-03-10T16:15:07.552Z  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
api01    | 2024-03-10T16:15:07.625Z  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
api02    | 2024-03-10T16:15:07.729Z  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
api01    | 2024-03-10T16:15:07.737Z  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
nginx-1  | 2024/03/10 16:15:08 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01    | 2024-03-10T16:15:09.532Z  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
api02    | 2024-03-10T16:15:09.632Z  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
nginx-1  | 2024/03/10 16:15:10 [error] 29#29: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.160.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:10 [error] 29#29: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.160.3:8080/clientes/1/extrato", host: "localhost:9999"
api01    | 2024-03-10T16:15:11.222Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path ''
api01    | 2024-03-10T16:15:11.233Z  INFO 1 --- [           main] c.a.r.RinhabackendApplication            : Started RinhabackendApplication in 23.599 seconds (process running for 26.408)
api02    | 2024-03-10T16:15:11.235Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path ''
api02    | 2024-03-10T16:15:11.244Z  INFO 1 --- [           main] c.a.r.RinhabackendApplication            : Started RinhabackendApplication in 23.72 seconds (process running for 26.419)
nginx-1  | 2024/03/10 16:15:12 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:14 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:16 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:18 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:15:20 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.160.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api01    | 2024-03-10T16:15:23.842Z  INFO 1 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
api01    | 2024-03-10T16:15:23.844Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api02    | 2024-03-10T16:15:23.847Z  INFO 1 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
api02    | 2024-03-10T16:15:23.849Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01    | 2024-03-10T16:15:23.858Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api02    | 2024-03-10T16:15:23.860Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api02 exited with code 0
api02 exited with code 143
api01 exited with code 0
api01 exited with code 143
db       | 2024-03-10 16:15:24.894 UTC [1] LOG:  received fast shutdown request
db       | 2024-03-10 16:15:24.898 UTC [1] LOG:  aborting any active transactions
db       | 2024-03-10 16:15:24.900 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db       | 2024-03-10 16:15:24.900 UTC [64] LOG:  shutting down
db       | 2024-03-10 16:15:24.902 UTC [64] LOG:  checkpoint starting: shutdown immediate
db       | 2024-03-10 16:15:24.972 UTC [64] LOG:  checkpoint complete: wrote 48 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.045 s, total=0.072 s; sync files=16, longest=0.019 s, average=0.003 s; distance=238 kB, estimate=238 kB; lsn=0/1958E60, redo lsn=0/1958E60
db       | 2024-03-10 16:15:24.976 UTC [1] LOG:  database system is shut down
db exited with code 0
