 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container java-cassiogangrel-postgres-1  Creating
 Container java-cassiogangrel-postgres-1  Created
 Container java-cassiogangrel-api01-1  Creating
 Container java-cassiogangrel-api01-1  Created
 Container java-cassiogangrel-api02-1  Creating
 Container java-cassiogangrel-api02-1  Created
 Container java-cassiogangrel-nginx-1  Creating
 Container java-cassiogangrel-nginx-1  Created
Attaching to api01-1, api02-1, nginx-1, postgres-1
postgres-1  | The files belonging to this database system will be owned by user "postgres".
postgres-1  | This user must also own the server process.
postgres-1  | 
postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-1  | The default database encoding has accordingly been set to "UTF8".
postgres-1  | The default text search configuration will be set to "english".
postgres-1  | 
postgres-1  | Data page checksums are disabled.
postgres-1  | 
postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-1  | creating subdirectories ... ok
postgres-1  | selecting dynamic shared memory implementation ... posix
postgres-1  | selecting default max_connections ... 100
postgres-1  | selecting default shared_buffers ... 128MB
postgres-1  | selecting default time zone ... Etc/UTC
postgres-1  | creating configuration files ... ok
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-12 23:26:03,199 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | 2024-02-12 23:26:03,206 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 2024-02-12 23:26:03,207 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-12 23:26:03,208 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-12 23:26:03,208 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-12 23:26:03,208 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 2024-02-12 23:26:03,210 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
api01-1     | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
api01-1     | 	at io.quarkus.runtime.Application.start(Application.java:101)
api01-1     | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
api01-1     | 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
api01-1     | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api01-1     | SQL State  : 08001
api01-1     | Error Code : 0
api01-1     | Message    : Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 
api01-1     | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
api01-1     | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
api01-1     | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
api01-1     | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
api01-1     | 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
api01-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
api01-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
api01-1     | 	... 7 more
api01-1     | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api01-1     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api01-1     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api01-1     | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api01-1     | 	at org.postgresql.Driver.connect(Driver.java:297)
api01-1     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api01-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api01-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api01-1     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api01-1     | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api01-1     | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api01-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api01-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api01-1     | Caused by: java.net.ConnectException: Connection refused
api01-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api01-1     | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api01-1     | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api01-1     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api01-1     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api01-1     | 	... 15 more
api01-1     | 
postgres-1  | running bootstrap script ... ok
api02-1     | __  ____  __  _____   ___  __ ____  ______ 
api02-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api02-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api02-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api02-1     | 2024-02-12 23:26:03,735 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api02-1     | 2024-02-12 23:26:03,737 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 2024-02-12 23:26:03,738 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api02-1     | 2024-02-12 23:26:03,738 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api02-1     | 2024-02-12 23:26:03,738 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api02-1     | 2024-02-12 23:26:03,787 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 2024-02-12 23:26:03,800 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
api02-1     | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
api02-1     | 	at io.quarkus.runtime.Application.start(Application.java:101)
api02-1     | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
api02-1     | 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
api02-1     | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api02-1     | SQL State  : 08001
api02-1     | Error Code : 0
api02-1     | Message    : Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 
api02-1     | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
api02-1     | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
api02-1     | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
api02-1     | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
api02-1     | 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
api02-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
api02-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
api02-1     | 	... 7 more
api02-1     | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api02-1     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api02-1     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api02-1     | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api02-1     | 	at org.postgresql.Driver.connect(Driver.java:297)
api02-1     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api02-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api02-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api02-1     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api02-1     | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api02-1     | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api02-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api02-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api02-1     | Caused by: java.net.ConnectException: Connection refused
api02-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1     | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1     | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api02-1     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api02-1     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api02-1     | 	... 15 more
api02-1     | 
postgres-1  | performing post-bootstrap initialization ... ok
postgres-1  | syncing data to disk ... ok
postgres-1  | 
postgres-1  | 
postgres-1  | Success. You can now start the database server using:
postgres-1  | 
postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres-1  | 
postgres-1  | initdb: warning: enabling "trust" authentication for local connections
postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
nginx-1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1     | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres-1  | waiting for server to start....2024-02-12 23:26:05.226 UTC [49] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1  | 2024-02-12 23:26:05.241 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-02-12 23:26:05.280 UTC [52] LOG:  database system was shut down at 2024-02-12 23:26:04 UTC
postgres-1  | 2024-02-12 23:26:05.320 UTC [49] LOG:  database system is ready to accept connections
api01-1 exited with code 0
postgres-1  |  done
postgres-1  | server started
api02-1 exited with code 0
postgres-1  | CREATE DATABASE
postgres-1  | 
postgres-1  | 
postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres-1  | 
postgres-1  | 2024-02-12 23:26:05.643 UTC [49] LOG:  received fast shutdown request
postgres-1  | waiting for server to shut down....2024-02-12 23:26:05.661 UTC [49] LOG:  aborting any active transactions
postgres-1  | 2024-02-12 23:26:05.667 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres-1  | 2024-02-12 23:26:05.668 UTC [50] LOG:  shutting down
postgres-1  | 2024-02-12 23:26:05.671 UTC [50] LOG:  checkpoint starting: shutdown immediate
postgres-1  | 2024-02-12 23:26:06.150 UTC [50] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.388 s, sync=0.073 s, total=0.481 s; sync files=301, longest=0.010 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913068, redo lsn=0/1913068
postgres-1  | 2024-02-12 23:26:06.161 UTC [49] LOG:  database system is shut down
postgres-1  |  done
postgres-1  | server stopped
postgres-1  | 
postgres-1  | PostgreSQL init process complete; ready for start up.
postgres-1  | 
postgres-1  | 2024-02-12 23:26:06.304 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1  | 2024-02-12 23:26:06.304 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2024-02-12 23:26:06.304 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2024-02-12 23:26:06.309 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-02-12 23:26:06.318 UTC [65] LOG:  database system was shut down at 2024-02-12 23:26:06 UTC
postgres-1  | 2024-02-12 23:26:06.326 UTC [1] LOG:  database system is ready to accept connections
api01-1 exited with code 0
api02-1 exited with code 0
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-12 23:26:06,810 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-12 23:26:06,810 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
nginx-1     | 2024/02/12 23:26:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.208.5:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.208.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/1/extrato", host: "localhost:9999"
api02-1     | __  ____  __  _____   ___  __ ____  ______ 
api02-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api02-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api02-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api02-1     | 2024-02-12 23:26:06,889 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api02-1     | __  ____  __  _____   ___  __ ____  ______ 
api02-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api02-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api02-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api02-1     | 2024-02-12 23:26:06,889 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.FlywayExecutor] (main) Database: jdbc:postgresql://postgres:5432/rinha (PostgreSQL 16.1)
api01-1     | 2024-02-12 23:26:06,901 INFO  [org.fly.cor.FlywayExecutor] (main) Database: jdbc:postgresql://postgres:5432/rinha (PostgreSQL 16.1)
api01-1     | 2024-02-12 23:26:06,903 WARNING [org.fly.cor.int.dat.bas.Database] (main) Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1     | 2024-02-12 23:26:06,903 WARNING [org.fly.cor.int.dat.bas.Database] (main) Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1     | 2024-02-12 23:26:06,907 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Schema history table "public"."flyway_schema_history" does not exist yet
api01-1     | 2024-02-12 23:26:06,907 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Schema history table "public"."flyway_schema_history" does not exist yet
api01-1     | 2024-02-12 23:26:06,907 INFO  [org.fly.cor.int.com.DbValidate] (main) Successfully validated 1 migration (execution time 00:00.002s)
api01-1     | 2024-02-12 23:26:06,907 INFO  [org.fly.cor.int.com.DbValidate] (main) Successfully validated 1 migration (execution time 00:00.002s)
api02-1     | 2024-02-12 23:26:06,911 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api02-1     | 2024-02-12 23:26:06,911 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api02-1     | 2024-02-12 23:26:06,911 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api02-1     | 2024-02-12 23:26:06,911 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api02-1     | 2024-02-12 23:26:06,911 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api02-1     | 2024-02-12 23:26:06,911 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api02-1     | 2024-02-12 23:26:06,912 INFO  [org.fly.cor.FlywayExecutor] (main) Database: jdbc:postgresql://postgres:5432/rinha (PostgreSQL 16.1)
api02-1     | 2024-02-12 23:26:06,912 INFO  [org.fly.cor.FlywayExecutor] (main) Database: jdbc:postgresql://postgres:5432/rinha (PostgreSQL 16.1)
api02-1     | 2024-02-12 23:26:06,914 WARNING [org.fly.cor.int.dat.bas.Database] (main) Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api02-1     | 2024-02-12 23:26:06,914 WARNING [org.fly.cor.int.dat.bas.Database] (main) Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1     | 2024-02-12 23:26:06,915 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Creating Schema History table "public"."flyway_schema_history" ...
api01-1     | 2024-02-12 23:26:06,915 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Creating Schema History table "public"."flyway_schema_history" ...
api02-1     | 2024-02-12 23:26:06,917 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Schema history table "public"."flyway_schema_history" does not exist yet
api02-1     | 2024-02-12 23:26:06,917 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Schema history table "public"."flyway_schema_history" does not exist yet
api02-1     | 2024-02-12 23:26:06,917 INFO  [org.fly.cor.int.com.DbValidate] (main) Successfully validated 1 migration (execution time 00:00.001s)
api02-1     | 2024-02-12 23:26:06,917 INFO  [org.fly.cor.int.com.DbValidate] (main) Successfully validated 1 migration (execution time 00:00.001s)
api01-1     | 2024-02-12 23:26:07,014 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": << Empty Schema >>
api01-1     | 2024-02-12 23:26:07,014 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": << Empty Schema >>
api01-1     | 2024-02-12 23:26:07,016 INFO  [org.fly.cor.int.com.DbMigrate] (main) Migrating schema "public" to version "1 - initialize db"
api01-1     | 2024-02-12 23:26:07,016 INFO  [org.fly.cor.int.com.DbMigrate] (main) Migrating schema "public" to version "1 - initialize db"
api01-1     | 2024-02-12 23:26:07,104 INFO  [org.fly.cor.int.com.DbMigrate] (main) Successfully applied 1 migration to schema "public", now at version v1 (execution time 00:00.062s)
api01-1     | 2024-02-12 23:26:07,104 INFO  [org.fly.cor.int.com.DbMigrate] (main) Successfully applied 1 migration to schema "public", now at version v1 (execution time 00:00.062s)
api01-1     | 2024-02-12 23:26:07,107 INFO  [io.quarkus] (main) rinha_e2 1.0.0 native (powered by Quarkus 3.7.2) started in 0.390s. Listening on: http://0.0.0.0:8080
api01-1     | 2024-02-12 23:26:07,107 INFO  [io.quarkus] (main) Profile prod activated. 
api01-1     | 2024-02-12 23:26:07,107 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, vertx]
api01-1     | 2024-02-12 23:26:07,107 INFO  [io.quarkus] (main) rinha_e2 1.0.0 native (powered by Quarkus 3.7.2) started in 0.390s. Listening on: http://0.0.0.0:8080
api01-1     | 2024-02-12 23:26:07,107 INFO  [io.quarkus] (main) Profile prod activated. 
api01-1     | 2024-02-12 23:26:07,107 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, vertx]
api02-1     | 2024-02-12 23:26:07,936 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 1
api02-1     | 2024-02-12 23:26:07,936 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 1
api02-1     | 2024-02-12 23:26:07,936 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
api02-1     | 2024-02-12 23:26:07,936 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
api02-1     | 2024-02-12 23:26:07,939 INFO  [io.quarkus] (main) rinha_e2 1.0.0 native (powered by Quarkus 3.7.2) started in 1.172s. Listening on: http://0.0.0.0:8080
api02-1     | 2024-02-12 23:26:07,939 INFO  [io.quarkus] (main) Profile prod activated. 
api02-1     | 2024-02-12 23:26:07,939 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, vertx]
api02-1     | 2024-02-12 23:26:07,939 INFO  [io.quarkus] (main) rinha_e2 1.0.0 native (powered by Quarkus 3.7.2) started in 1.172s. Listening on: http://0.0.0.0:8080
api02-1     | 2024-02-12 23:26:07,939 INFO  [io.quarkus] (main) Profile prod activated. 
api02-1     | 2024-02-12 23:26:07,939 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, vertx]
nginx-1     | 2024/02/12 23:26:08 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:10 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:12 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:14 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:16 [error] 29#29: *9 no live upstreams while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:18 [error] 29#29: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:29 [error] 29#29: *117 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:40 [error] 29#29: *422 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:26:51 [error] 29#29: *1347 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:27:02 [error] 29#29: *2946 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:27:13 [error] 29#29: *5231 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:27:24 [error] 29#29: *8190 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:27:35 [error] 29#29: *11831 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:27:46 [error] 29#29: *16150 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:27:57 [error] 29#29: *21145 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:28:08 [error] 29#29: *26828 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:28:19 [error] 29#29: *33189 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:24 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:25 [alert] 29#29: 400 worker_connections are not enough
nginx-1     | 2024/02/12 23:28:30 [error] 29#29: *39956 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:28:41 [error] 29#29: *47437 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:28:52 [error] 29#29: *54918 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:29:03 [error] 29#29: *62395 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:29:14 [error] 29#29: *69876 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:29:25 [error] 29#29: *77361 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:29:36 [error] 29#29: *84842 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:29:47 [error] 29#29: *92323 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:29:58 [error] 29#29: *99801 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:30:09 [error] 29#29: *107281 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:30:20 [error] 29#29: *114766 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/12 23:30:31 [error] 29#29: *122243 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.208.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1     | 2024-02-12 23:30:37,156 INFO  [io.quarkus] (main) rinha_e2 stopped in 0.014s
api02-1     | 2024-02-12 23:30:37,156 INFO  [io.quarkus] (main) rinha_e2 stopped in 0.014s
api02-1 exited with code 0
api02-1 exited with code 143
api01-1     | 2024-02-12 23:30:37,771 INFO  [io.quarkus] (Shutdown thread) rinha_e2 stopped in 0.011s
api01-1     | 2024-02-12 23:30:37,771 INFO  [io.quarkus] (Shutdown thread) rinha_e2 stopped in 0.011s
api01-1 exited with code 0
api01-1 exited with code 143
postgres-1  | 2024-02-12 23:30:38.824 UTC [1] LOG:  received fast shutdown request
postgres-1  | 2024-02-12 23:30:38.827 UTC [1] LOG:  aborting any active transactions
postgres-1  | 2024-02-12 23:30:38.830 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
postgres-1  | 2024-02-12 23:30:38.830 UTC [63] LOG:  shutting down
postgres-1  | 2024-02-12 23:30:38.832 UTC [63] LOG:  checkpoint starting: shutdown immediate
postgres-1  | 2024-02-12 23:30:38.933 UTC [63] LOG:  checkpoint complete: wrote 984 buffers (6.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.075 s, sync=0.017 s, total=0.103 s; sync files=78, longest=0.006 s, average=0.001 s; distance=22723 kB, estimate=22723 kB; lsn=0/2F43D78, redo lsn=0/2F43D78
postgres-1  | 2024-02-12 23:30:38.940 UTC [1] LOG:  database system is shut down
postgres-1 exited with code 0
