 Network rinhav2  Creating
 Network rinhav2  Created
 Container gavageovanni-db-1  Creating
 Container gavageovanni-db-1  Created
 Container gavageovanni-api02-1  Creating
 Container gavageovanni-api01-1  Creating
 Container gavageovanni-api01-1  Created
 Container gavageovanni-api02-1  Created
 Container gavageovanni-nginx-1  Creating
 Container gavageovanni-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api02-1  | panic: runtime error: invalid memory address or nil pointer dereference
api02-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x85255c]
api02-1  | 
api02-1  | goroutine 1 [running]:
api02-1  | github.com/labstack/echo/v4.(*Echo).Use(0x0, {0xc0000b5e98?, 0x1?, 0x1?})
api02-1  | 	/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:474 +0x1c
api02-1  | main.main()
api02-1  | 	/app/main.go:12 +0x1e9
api01-1  | panic: runtime error: invalid memory address or nil pointer dereference
api01-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x85255c]
api01-1  | 
api01-1  | goroutine 1 [running]:
api01-1  | github.com/labstack/echo/v4.(*Echo).Use(0x0, {0xc0004a7e98?, 0x1?, 0x1?})
api01-1  | 	/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:474 +0x1c
api01-1  | main.main()
api01-1  | 	/app/main.go:12 +0x1e9
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-13 23:13:05.561 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-13 23:13:05.561 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-13 23:13:05.564 UTC [51] LOG:  database system was shut down at 2024-02-13 23:13:04 UTC
db-1     | 2024-02-13 23:13:05.569 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
db-1     | DO
db-1     | CREATE FUNCTION
db-1     | 
db-1     | 
db-1     | 2024-02-13 23:13:05.889 UTC [48] LOG:  received fast shutdown request
db-1     | waiting for server to shut down...2024-02-13 23:13:05.889 UTC [48] LOG:  aborting any active transactions
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | .2024-02-13 23:13:05.899 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-13 23:13:05.900 UTC [49] LOG:  shutting down
db-1     | 2024-02-13 23:13:05.900 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-13 23:13:05.909 UTC [49] LOG:  checkpoint complete: wrote 934 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.001 s, total=0.009 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4286 kB, estimate=4286 kB; lsn=0/191A3B8, redo lsn=0/191A3B8
db-1     | 2024-02-13 23:13:05.923 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-13 23:13:06.054 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-13 23:13:06.054 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-13 23:13:06.054 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-13 23:13:06.054 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-13 23:13:06.057 UTC [66] LOG:  database system was shut down at 2024-02-13 23:13:05 UTC
db-1     | 2024-02-13 23:13:06.062 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/13 23:13:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:13:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.4:8080/clientes/1/extrato", host: "localhost:9999"
api01-1 exited with code 0
api02-1 exited with code 0
api02-1  | 
api02-1  |    ____    __
api02-1  |   / __/___/ /  ___
api02-1  |  / _// __/ _ \/ _ \
api02-1  | /___/\__/_//_/\___/ v4.11.4
api02-1  | High performance, minimalist Go web framework
api02-1  | https://echo.labstack.com
api02-1  | ____________________________________O/_______
api02-1  |                                     O\
api02-1  | ⇨ http server started on [::]:8080
api01-1  | 
api01-1  |    ____    __
api01-1  |   / __/___/ /  ___
api01-1  |  / _// __/ _ \/ _ \
api01-1  | /___/\__/_//_/\___/ v4.11.4
api01-1  | High performance, minimalist Go web framework
api01-1  | https://echo.labstack.com
api01-1  | ____________________________________O/_______
api01-1  |                                     O\
api01-1  | ⇨ http server started on [::]:8080
nginx-1  | 2024/02/13 23:13:08 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:13:10 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:13:12 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:13:14 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/13 23:13:16 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api01-1 exited with code 0
api01-1 exited with code 2
api02-1 exited with code 0
api02-1 exited with code 2
db-1     | 2024-02-13 23:17:36.739 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-13 23:17:36.739 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-13 23:17:36.742 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-13 23:17:36.743 UTC [64] LOG:  shutting down
db-1     | 2024-02-13 23:17:36.743 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-13 23:17:36.749 UTC [64] LOG:  checkpoint complete: wrote 831 buffers (5.1%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.006 s, sync=0.001 s, total=0.007 s; sync files=0, longest=0.000 s, average=0.000 s; distance=16058 kB, estimate=16058 kB; lsn=0/28C8E08, redo lsn=0/28C8E08
db-1     | 2024-02-13 23:17:36.762 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
