 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container franklaercio-db-1  Creating
 Container franklaercio-db-1  Created
 Container franklaercio-api02-1  Creating
 Container franklaercio-api01-1  Creating
 Container franklaercio-api02-1  Created
 Container franklaercio-api01-1  Created
 Container franklaercio-nginx-1  Creating
 Container franklaercio-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-25 21:05:29.401 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-25 21:05:29.404 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-25 21:05:29.414 UTC [51] LOG:  database system was shut down at 2024-02-25 21:05:28 UTC
db-1     | 2024-02-25 21:05:29.421 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | INSERT 0 1
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-25 21:05:29.661 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-25 21:05:29.664 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-25 21:05:29.665 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-25 21:05:29.667 UTC [49] LOG:  shutting down
db-1     | 2024-02-25 21:05:29.669 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-25 21:05:30.157 UTC [49] LOG:  checkpoint complete: wrote 938 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.371 s, sync=0.108 s, total=0.490 s; sync files=308, longest=0.074 s, average=0.001 s; distance=4292 kB, estimate=4292 kB; lsn=0/191BCA8, redo lsn=0/191BCA8
db-1     | 2024-02-25 21:05:30.162 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-25 21:05:30.286 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-25 21:05:30.287 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-25 21:05:30.287 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-25 21:05:30.292 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-25 21:05:30.301 UTC [66] LOG:  database system was shut down at 2024-02-25 21:05:30 UTC
db-1     | 2024-02-25 21:05:30.307 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/25 21:05:31 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:31 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:33 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:35 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-25T21:05:36.828Z  INFO 1 --- [           main] com.github.rinha.Application             : Starting Application v1.0.0 using Java 21.0.1 with PID 1 (/app/app.jar started by root in /)
api01-1  | 2024-02-25T21:05:36.827Z  INFO 1 --- [           main] com.github.rinha.Application             : Starting Application v1.0.0 using Java 21.0.1 with PID 1 (/app/app.jar started by root in /)
api02-1  | 2024-02-25T21:05:36.921Z  INFO 1 --- [           main] com.github.rinha.Application             : No active profile set, falling back to 1 default profile: "default"
api01-1  | 2024-02-25T21:05:36.921Z  INFO 1 --- [           main] com.github.rinha.Application             : No active profile set, falling back to 1 default profile: "default"
nginx-1  | 2024/02/25 21:05:37 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:39 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:41 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:43 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:43 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.23.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:45 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:47 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/25 21:05:49 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api01-1  | 2024-02-25T21:05:51.215Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
api01-1  | 2024-02-25T21:05:51.328Z  INFO 1 --- [           main] com.github.rinha.Application             : Started Application in 18.707 seconds (process running for 23.063)
nginx-1  | 2024/02/25 21:05:51 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-25T21:05:52.023Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
api02-1  | 2024-02-25T21:05:52.119Z  INFO 1 --- [           main] com.github.rinha.Application             : Started Application in 19.505 seconds (process running for 23.757)
nginx-1  | 2024/02/25 21:05:53 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 172.23.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1  | 2024-02-25T21:05:56.423Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api02-1  | 2024-02-25T21:05:57.721Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@99cab35
api02-1  | 2024-02-25T21:05:57.722Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api01-1  | 2024-02-25T21:06:04.630Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api01-1  | 2024-02-25T21:06:06.216Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@7d966b9e
api01-1  | 2024-02-25T21:06:06.218Z  INFO 1 --- [or-http-epoll-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
nginx-1 exited with code 0
nginx-1 exited with code 0
api01-1  | 2024-02-25T21:10:16.228Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api02-1  | 2024-02-25T21:10:16.229Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01-1  | 2024-02-25T21:10:16.240Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api02-1  | 2024-02-25T21:10:16.241Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api02-1 exited with code 0
api02-1 exited with code 143
api01-1 exited with code 0
api01-1 exited with code 143
db-1     | 2024-02-25 21:10:17.180 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-25 21:10:17.210 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-25 21:10:17.212 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-25 21:10:17.213 UTC [64] LOG:  shutting down
db-1     | 2024-02-25 21:10:17.216 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-25 21:10:17.365 UTC [64] LOG:  checkpoint complete: wrote 742 buffers (4.5%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.010 s, sync=0.123 s, total=0.152 s; sync files=29, longest=0.084 s, average=0.005 s; distance=19715 kB, estimate=19715 kB; lsn=0/2C5CB60, redo lsn=0/2C5CB60
db-1     | 2024-02-25 21:10:17.369 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
