 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container vkobinski-db-1  Creating
 Container vkobinski-db-1  Created
 Container vkobinski-api02-1  Creating
 Container vkobinski-api01-1  Creating
 Container vkobinski-api01-1  Created
 Container vkobinski-api02-1  Created
 Container vkobinski-nginx-1  Creating
 Container vkobinski-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api01-1  | connections: 30
api02-1  | connections: 30
db-1     | performing post-bootstrap initialization ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | postgres: could not access the server configuration file "/etc/postgresql/postgresql.conf": No such file or directory
db-1 exited with code 2
api01-1  | thread 'main' panicked at src/main.rs:23:112:
api01-1  | called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })
api01-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
api02-1  | thread 'main' panicked at src/main.rs:23:112:
api02-1  | called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })
api02-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
api01-1 exited with code 101
api02-1 exited with code 101
nginx-1  | 2024/03/10 18:09:57 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:00 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:02 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:04 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:06 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:11 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:15 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:17 [error] 29#29: *10 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:19 [error] 29#29: *11 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:21 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:26 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:29 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:31 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:33 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:35 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:40 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:43 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:45 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:47 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:49 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:54 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:57 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:10:59 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:11:01 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 18:11:03 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
