 Container thusspokebieu-activej-db-1  Creating
 Container thusspokebieu-activej-db-1  Created
 Container thusspokebieu-activej-api02-1  Creating
 Container thusspokebieu-activej-api01-1  Creating
 Container thusspokebieu-activej-api01-1  Created
 Container thusspokebieu-activej-api02-1  Created
 Container thusspokebieu-activej-nginx-1  Creating
 Container thusspokebieu-activej-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api01-1  | SLF4J: No SLF4J providers were found.
api01-1  | SLF4J: Defaulting to no-operation (NOP) logger implementation
api01-1  | SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
api02-1  | SLF4J: No SLF4J providers were found.
api02-1  | SLF4J: Defaulting to no-operation (NOP) logger implementation
api02-1  | SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-12 01:16:19.761 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-12 01:16:19.814 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-12 01:16:19.927 UTC [51] LOG:  database system was shut down at 2024-02-12 01:16:18 UTC
db-1     | 2024-02-12 01:16:19.958 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | DO
db-1     | CREATE FUNCTION
db-1     | CREATE FUNCTION
db-1     | 
db-1     | 
db-1     | 2024-02-12 01:16:20.624 UTC [48] LOG:  received fast shutdown request
db-1     | waiting for server to shut down....2024-02-12 01:16:20.639 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-12 01:16:20.642 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-12 01:16:20.643 UTC [49] LOG:  shutting down
db-1     | 2024-02-12 01:16:20.669 UTC [49] LOG:  checkpoint starting: shutdown immediate
api02-1  | Exception in thread "main" io.activej.inject.binding.DIException: Failed to call method java.sql.Connection github.mess.App.dataSourcePg(io.activej.config.Config) throws java.sql.SQLException,java.io.IOException
api02-1  | 	at io.activej.inject.util.ReflectionUtils.lambda$bindingFromMethod$9(ReflectionUtils.java:347)
api02-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:69)
api02-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api02-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:67)
api02-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api02-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:67)
api02-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api02-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:67)
api02-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api02-1  | 	at io.activej.inject.util.ReflectionUtils$1$1.initInstance(ReflectionUtils.java:269)
api02-1  | 	at io.activej.inject.impl.Preprocessor$InstanceInjectorImpl.injectInto(Preprocessor.java:597)
api02-1  | 	at io.activej.launcher.Launcher.postInjectInstances(Launcher.java:220)
api02-1  | 	at io.activej.launcher.Launcher.launch(Launcher.java:150)
api02-1  | 	at github.mess.App.main(App.java:53)
api01-1  | Exception in thread "main" io.activej.inject.binding.DIException: Failed to call method java.sql.Connection github.mess.App.dataSourcePg(io.activej.config.Config) throws java.sql.SQLException,java.io.IOException
api01-1  | 	at io.activej.inject.util.ReflectionUtils.lambda$bindingFromMethod$9(ReflectionUtils.java:347)
api01-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:69)
api01-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api01-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:67)
api01-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api01-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:67)
api01-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api01-1  | 	at io.activej.inject.binding.Bindings$BindingToConstructorN$1.doCreateInstance(Bindings.java:67)
api01-1  | 	at io.activej.inject.impl.AbstractRootCompiledBinding.getInstance(AbstractRootCompiledBinding.java:40)
api01-1  | 	at io.activej.inject.util.ReflectionUtils$1$1.initInstance(ReflectionUtils.java:269)
api01-1  | 	at io.activej.inject.impl.Preprocessor$InstanceInjectorImpl.injectInto(Preprocessor.java:597)
api01-1  | 	at io.activej.launcher.Launcher.postInjectInstances(Launcher.java:220)
api01-1  | 	at io.activej.launcher.Launcher.launch(Launcher.java:150)
api01-1  | 	at github.mess.App.main(App.java:53)
api02-1  | Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api02-1  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api02-1  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api02-1  | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api02-1  | 	at org.postgresql.Driver.connect(Driver.java:297)
api02-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
api02-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
api02-1  | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
api02-1  | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
api02-1  | 	at github.mess.App.dataSourcePg(App.java:29)
api02-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
api02-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
api02-1  | 	at io.activej.inject.util.ReflectionUtils.lambda$bindingFromMethod$9(ReflectionUtils.java:340)
api02-1  | 	... 13 more
api01-1  | Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api01-1  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api01-1  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api01-1  | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api01-1  | 	at org.postgresql.Driver.connect(Driver.java:297)
api01-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
api01-1  | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
api01-1  | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
api01-1  | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
api01-1  | 	at github.mess.App.dataSourcePg(App.java:29)
api01-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
api01-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
api01-1  | 	at io.activej.inject.util.ReflectionUtils.lambda$bindingFromMethod$9(ReflectionUtils.java:340)
api02-1  | Caused by: java.net.ConnectException: Connection refused
api02-1  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
api02-1  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1  | 	at java.base/java.net.Socket.connect(Socket.java:751)
api02-1  | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api02-1  | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api02-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api02-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api02-1  | 	... 25 more
api01-1  | 	... 13 more
api01-1  | Caused by: java.net.ConnectException: Connection refused
api01-1  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
api01-1  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api01-1  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api01-1  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api01-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api01-1  | 	at java.base/java.net.Socket.connect(Socket.java:751)
api01-1  | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api01-1  | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api01-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api01-1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api01-1  | 	... 25 more
api01-1 exited with code 1
api02-1 exited with code 1
db-1     | ..2024-02-12 01:16:22.655 UTC [49] LOG:  checkpoint complete: wrote 949 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.002 s, sync=0.382 s, total=2.013 s; sync files=309, longest=0.032 s, average=0.002 s; distance=4303 kB, estimate=4303 kB; lsn=0/191E940, redo lsn=0/191E940
db-1     | 2024-02-12 01:16:22.664 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-12 01:16:22.780 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-12 01:16:22.781 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-12 01:16:22.781 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-12 01:16:22.801 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-12 01:16:22.821 UTC [66] LOG:  database system was shut down at 2024-02-12 01:16:22 UTC
db-1     | 2024-02-12 01:16:22.835 UTC [1] LOG:  database system is ready to accept connections
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-12 01:17:01.548 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-12 01:17:01.550 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-12 01:17:01.553 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-12 01:17:01.555 UTC [64] LOG:  shutting down
db-1     | 2024-02-12 01:17:01.557 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-12 01:17:01.580 UTC [64] LOG:  checkpoint complete: wrote 42 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.005 s, total=0.025 s; sync files=11, longest=0.003 s, average=0.001 s; distance=238 kB, estimate=238 kB; lsn=0/195A4D8, redo lsn=0/195A4D8
db-1     | 2024-02-12 01:17:01.585 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
