 Network felipebossolani-dotnet_app-network  Creating
 Network felipebossolani-dotnet_app-network  Created
 Container db  Creating
 Container db  Created
 Container api2  Creating
 Container api1  Creating
 Container api2  Created
 Container api1  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api1, api2, db, nginx
db     | The files belonging to this database system will be owned by user "postgres".
db     | This user must also own the server process.
db     | 
db     | The database cluster will be initialized with locale "en_US.utf8".
db     | The default database encoding has accordingly been set to "UTF8".
db     | The default text search configuration will be set to "english".
db     | 
db     | Data page checksums are disabled.
db     | 
db     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db     | creating subdirectories ... ok
db     | selecting dynamic shared memory implementation ... posix
db     | selecting default max_connections ... 100
db     | selecting default shared_buffers ... 128MB
db     | selecting default time zone ... Etc/UTC
db     | creating configuration files ... ok
db     | running bootstrap script ... ok
db     | performing post-bootstrap initialization ... ok
db     | syncing data to disk ... ok
db     | 
db     | 
db     | Success. You can now start the database server using:
db     | 
db     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db     | 
db     | initdb: warning: enabling "trust" authentication for local connections
db     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db     | waiting for server to start....2024-02-19 05:32:41.588 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db     | 2024-02-19 05:32:41.588 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db     | 2024-02-19 05:32:41.615 UTC [51] LOG:  database system was shut down at 2024-02-19 05:32:39 UTC
db     | 2024-02-19 05:32:41.618 UTC [48] LOG:  database system is ready to accept connections
db     |  done
db     | server started
db     | CREATE DATABASE
db     | 
db     | 
db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_ddl.sql
db     | CREATE TABLE
db     | CREATE TABLE
db     | ALTER TABLE
db     | CREATE INDEX
db     | 
db     | 
db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/02_dml.sql
db     | DELETE 0
db     | DELETE 0
db     | INSERT 0 5
db     | CREATE FUNCTION
db     | 
db     | 
db     | waiting for server to shut down....2024-02-19 05:32:41.918 UTC [48] LOG:  received fast shutdown request
db     | 2024-02-19 05:32:41.919 UTC [48] LOG:  aborting any active transactions
db     | 2024-02-19 05:32:41.920 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db     | 2024-02-19 05:32:41.921 UTC [49] LOG:  shutting down
db     | 2024-02-19 05:32:41.921 UTC [49] LOG:  checkpoint starting: shutdown immediate
db     | 2024-02-19 05:32:41.927 UTC [49] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.006 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4287 kB, estimate=4287 kB; lsn=0/191A7E8, redo lsn=0/191A7E8
db     | 2024-02-19 05:32:41.933 UTC [48] LOG:  database system is shut down
db     |  done
db     | server stopped
db     | 
db     | PostgreSQL init process complete; ready for start up.
db     | 
db     | 2024-02-19 05:32:42.045 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db     | 2024-02-19 05:32:42.045 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db     | 2024-02-19 05:32:42.045 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db     | 2024-02-19 05:32:42.046 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db     | 2024-02-19 05:32:42.047 UTC [68] LOG:  database system was shut down at 2024-02-19 05:32:41 UTC
db     | 2024-02-19 05:32:42.050 UTC [1] LOG:  database system is ready to accept connections
db     | 2024-02-19 05:32:43.873 UTC [78] FATAL:  role "rinha" does not exist
nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
api2   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
api2   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
api1   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
api1   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
api2   | info: Microsoft.Hosting.Lifetime[14]
api2   |       Now listening on: http://[::]:8080
api1   | info: Microsoft.Hosting.Lifetime[14]
api1   |       Now listening on: http://[::]:8080
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Application started. Press Ctrl+C to shut down.
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Hosting environment: Production
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Content root path: /app
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Application started. Press Ctrl+C to shut down.
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Hosting environment: Production
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Content root path: /app
db     | 2024-02-19 05:32:48.954 UTC [86] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:32:52 [error] 29#29: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:32:52 [error] 32#32: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:32:52 [error] 31#31: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:32:52 [error] 31#31: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:32:54.030 UTC [104] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:32:54 [error] 30#30: *62 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:32:59.110 UTC [123] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:03 [error] 29#29: *356 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:04.188 UTC [131] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:04 [error] 32#32: *385 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /clientes/4/extrato HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/extrato", host: "localhost:9999"
nginx  | 2024/02/19 05:33:04 [error] 31#31: *418 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:05 [error] 30#30: *443 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:09.264 UTC [138] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:33:14.329 UTC [145] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:14 [error] 29#29: *1130 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:15 [error] 31#31: *1199 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:15 [error] 32#32: *1290 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:16 [error] 30#30: *1355 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:19.407 UTC [153] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:33:24.475 UTC [161] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:25 [error] 29#29: *2540 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:26 [error] 32#32: *2701 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:26 [error] 31#31: *2734 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:27 [error] 30#30: *2895 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:29.561 UTC [168] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:33:34.631 UTC [175] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:36 [error] 29#29: *4720 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:37 [error] 32#32: *4881 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:37 [error] 31#31: *4914 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:38 [error] 30#30: *5203 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:39.700 UTC [182] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:33:44.774 UTC [190] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:47 [error] 29#29: *7540 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:48 [error] 31#31: *7739 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:48 [error] 32#32: *7830 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:49 [error] 30#30: *8035 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:49.843 UTC [197] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:33:54.915 UTC [204] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:33:58 [error] 29#29: *11000 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:59 [error] 32#32: *11289 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:33:59 [error] 31#31: *11322 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:33:59.991 UTC [211] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:00 [error] 30#30: *11635 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:05.072 UTC [219] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:09 [error] 29#29: *15102 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:10 [error] 32#32: *15517 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:10 [error] 31#31: *15550 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:10.159 UTC [226] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:11 [error] 30#30: *15967 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:15.237 UTC [233] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:20 [error] 29#29: *19968 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:20.316 UTC [240] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:21 [error] 32#32: *20395 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:21 [error] 31#31: *20418 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:22 [error] 30#30: *20963 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:25.417 UTC [248] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:34:30.518 UTC [255] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:31 [error] 29#29: *25476 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:32 [error] 32#32: *26021 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:32 [error] 31#31: *26054 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:33 [error] 30#30: *26599 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:35.618 UTC [262] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:34:40.719 UTC [269] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:42 [error] 29#29: *31634 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:43 [error] 32#32: *32297 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:43 [error] 31#31: *32328 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:44 [error] 30#30: *32875 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:45.820 UTC [277] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:34:50.923 UTC [284] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:34:53 [error] 29#29: *38538 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:54 [error] 32#32: *39213 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:54 [error] 31#31: *39246 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:34:55 [error] 30#30: *39919 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:34:56.023 UTC [291] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:35:01.127 UTC [298] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:04 [error] 29#29: *45969 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:05 [error] 32#32: *46645 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:05 [error] 31#31: *46663 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:06 [error] 30#30: *47347 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:06.224 UTC [306] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:35:11.327 UTC [313] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:15 [error] 29#29: *53430 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:16 [error] 31#31: *54108 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:16 [error] 32#32: *54183 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:16.422 UTC [320] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:17 [error] 30#30: *54793 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:21.522 UTC [327] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:26 [error] 29#29: *60937 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:26.627 UTC [335] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:27 [error] 32#32: *61616 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /clientes/4/extrato HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/extrato", host: "localhost:9999"
nginx  | 2024/02/19 05:35:27 [error] 31#31: *61650 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:28 [error] 30#30: *62313 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:31.723 UTC [342] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:35:36.827 UTC [348] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:37 [error] 29#29: *68398 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:38 [error] 32#32: *69076 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:38 [error] 31#31: *69088 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:39 [error] 30#30: *69767 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:41.921 UTC [355] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:35:47.026 UTC [363] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:48 [error] 29#29: *75924 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:49 [error] 32#32: *76604 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:49 [error] 31#31: *76644 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:35:50 [error] 30#30: *77315 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:35:52.126 UTC [370] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:35:57.229 UTC [377] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:35:59 [error] 29#29: *83364 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:00 [error] 32#32: *84047 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:00 [error] 31#31: *84064 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:01 [error] 30#30: *84743 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:02.326 UTC [385] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:36:07.428 UTC [393] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:10 [error] 29#29: *90920 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:11 [error] 31#31: *91533 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:11 [error] 32#32: *91594 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:12 [error] 30#30: *92285 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:12.524 UTC [400] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:36:17.626 UTC [408] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:21 [error] 29#29: *98348 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:22 [error] 32#32: *99023 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:22 [error] 31#31: *99038 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /clientes/3/extrato HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/extrato", host: "localhost:9999"
db     | 2024-02-19 05:36:22.725 UTC [416] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:23 [error] 30#30: *99727 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:27.827 UTC [423] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:32 [error] 29#29: *105904 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:32.928 UTC [430] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:33 [error] 31#31: *106499 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:33 [error] 32#32: *106577 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:34 [error] 30#30: *107179 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:38.031 UTC [438] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:43 [error] 29#29: *113322 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /clientes/3/extrato HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/extrato", host: "localhost:9999"
db     | 2024-02-19 05:36:43.128 UTC [445] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:44 [error] 32#32: *114005 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /clientes/5/extrato HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/5/extrato", host: "localhost:9999"
nginx  | 2024/02/19 05:36:44 [error] 31#31: *114024 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:45 [error] 30#30: *114707 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:48.230 UTC [452] FATAL:  role "rinha" does not exist
db     | 2024-02-19 05:36:53.327 UTC [459] FATAL:  role "rinha" does not exist
nginx  | 2024/02/19 05:36:54 [error] 29#29: *120786 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/4/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:55 [error] 31#31: *121467 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:55 [error] 32#32: *121562 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
nginx  | 2024/02/19 05:36:56 [error] 30#30: *122149 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.24.0.3:8081/clientes/1/transacoes", host: "localhost:9999"
db     | 2024-02-19 05:36:58.414 UTC [467] FATAL:  role "rinha" does not exist
nginx exited with code 0
nginx exited with code 0
api1   | info: Microsoft.Hosting.Lifetime[0]
api1   |       Application is shutting down...
api2   | info: Microsoft.Hosting.Lifetime[0]
api2   |       Application is shutting down...
api1 exited with code 0
api1 exited with code 0
api2 exited with code 0
api2 exited with code 0
db     | 2024-02-19 05:37:01.829 UTC [1] LOG:  received fast shutdown request
db     | 2024-02-19 05:37:01.829 UTC [1] LOG:  aborting any active transactions
db     | 2024-02-19 05:37:01.831 UTC [1] LOG:  background worker "logical replication launcher" (PID 71) exited with exit code 1
db     | 2024-02-19 05:37:01.831 UTC [66] LOG:  shutting down
db     | 2024-02-19 05:37:01.831 UTC [66] LOG:  checkpoint starting: shutdown immediate
db     | 2024-02-19 05:37:01.835 UTC [66] LOG:  checkpoint complete: wrote 883 buffers (5.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=2855 kB, estimate=2855 kB; lsn=0/1BE4658, redo lsn=0/1BE4658
db     | 2024-02-19 05:37:01.841 UTC [1] LOG:  database system is shut down
db exited with code 0
